/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratori1digitales3;

import gnu.io.CommPort;
import gnu.io.CommPortIdentifier;
import gnu.io.PortInUseException;
import gnu.io.SerialPort;
import gnu.io.UnsupportedCommOperationException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.CategoryItemLabelGenerator;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.labels.StandardXYItemLabelGenerator;
import org.jfree.chart.labels.XYItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author eldoc
 */
public class MainFrame extends javax.swing.JFrame implements Runnable {

    Thread hilo1;
    Thread hilo2;
    String port;

    ArrayList<CommPortIdentifier> arrayListPuertosSerial;

    CommPortIdentifier myCPI = null;
    CommPort puerto;
    private SerialPort mySP;

    private Scanner mySC;
    private PrintStream myPS;

    JFreeChart freeChart;
    DefaultCategoryDataset Datos = new DefaultCategoryDataset();
    ArrayList arrayVoltaje = new ArrayList();

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnConectar = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        cbxComboboxPuertos = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        panelCargando = new javax.swing.JPanel();
        lblCargando = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        panelGraficaVoltaje = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblVoltajePotenciometro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texAreaTecladoMatricial = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPrimeraLineaLcd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSegundaLineaLcd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sliderPwm = new javax.swing.JSlider();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 590));
        setMinimumSize(new java.awt.Dimension(1200, 590));
        setPreferredSize(new java.awt.Dimension(1200, 590));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 590));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setMaximumSize(new java.awt.Dimension(1200, 24));
        jPanel6.setPreferredSize(new java.awt.Dimension(1200, 24));
        jPanel6.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(33, 33, 33));
        jPanel5.setMaximumSize(new java.awt.Dimension(1200, 54));
        jPanel5.setMinimumSize(new java.awt.Dimension(1200, 54));
        jPanel5.setName(""); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(1200, 54));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LABORATORIO DE DIGITALES");

        btnConectar.setBackground(new java.awt.Color(244, 157, 18));
        btnConectar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConectar.setText("Conectar");
        btnConectar.setBorderPainted(false);
        btnConectar.setEnabled(false);
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        btnDesconectar.setBackground(new java.awt.Color(244, 157, 18));
        btnDesconectar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDesconectar.setText("Desconectar");
        btnDesconectar.setBorderPainted(false);
        btnDesconectar.setDefaultCapable(false);
        btnDesconectar.setEnabled(false);
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(244, 157, 18));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActualizar.setText("Actualizar puertos");
        btnActualizar.setBorderPainted(false);
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        cbxComboboxPuertos.setBackground(new java.awt.Color(244, 157, 18));
        cbxComboboxPuertos.setEnabled(false);
        cbxComboboxPuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxComboboxPuertosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(416, 416, 416)
                .addComponent(cbxComboboxPuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesconectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConectar)
                        .addComponent(btnDesconectar)
                        .addComponent(btnActualizar)
                        .addComponent(cbxComboboxPuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(774, 774, 774))
        );

        jPanel4.setMaximumSize(new java.awt.Dimension(1200, 930));
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 930));

        panelCargando.setBackground(new java.awt.Color(49, 48, 48));
        panelCargando.setMaximumSize(new java.awt.Dimension(1200, 465));
        panelCargando.setMinimumSize(new java.awt.Dimension(1200, 465));
        panelCargando.setPreferredSize(new java.awt.Dimension(1200, 465));

        lblCargando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCargando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratori1digitales3/images/cargando.gif"))); // NOI18N

        javax.swing.GroupLayout panelCargandoLayout = new javax.swing.GroupLayout(panelCargando);
        panelCargando.setLayout(panelCargandoLayout);
        panelCargandoLayout.setHorizontalGroup(
            panelCargandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargandoLayout.createSequentialGroup()
                .addGap(461, 461, 461)
                .addComponent(lblCargando, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCargandoLayout.setVerticalGroup(
            panelCargandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargandoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblCargando, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        panelContenido.setBackground(new java.awt.Color(204, 204, 204));
        panelContenido.setMaximumSize(new java.awt.Dimension(1200, 465));
        panelContenido.setPreferredSize(new java.awt.Dimension(1200, 465));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        panelGraficaVoltaje.setBackground(new java.awt.Color(204, 204, 204));
        panelGraficaVoltaje.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelGraficaVoltajeLayout = new javax.swing.GroupLayout(panelGraficaVoltaje);
        panelGraficaVoltaje.setLayout(panelGraficaVoltajeLayout);
        panelGraficaVoltajeLayout.setHorizontalGroup(
            panelGraficaVoltajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        panelGraficaVoltajeLayout.setVerticalGroup(
            panelGraficaVoltajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        jLabel7.setBackground(new java.awt.Color(72, 72, 72));
        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("Voltaje de Potenciometro");

        lblVoltajePotenciometro.setBackground(new java.awt.Color(72, 72, 72));
        lblVoltajePotenciometro.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblVoltajePotenciometro.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVoltajePotenciometro, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelGraficaVoltaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVoltajePotenciometro)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGraficaVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        texAreaTecladoMatricial.setBackground(new java.awt.Color(153, 153, 153));
        texAreaTecladoMatricial.setColumns(20);
        texAreaTecladoMatricial.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        texAreaTecladoMatricial.setLineWrap(true);
        texAreaTecladoMatricial.setRows(5);
        jScrollPane1.setViewportView(texAreaTecladoMatricial);

        jPanel8.setBackground(new java.awt.Color(72, 72, 72));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Recibir teclado matricial");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Primera linea de 16 caracteres  ");

        txtPrimeraLineaLcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimeraLineaLcdActionPerformed(evt);
            }
        });

        jLabel6.setText("Segunda linea de 16 caracteres");

        txtSegundaLineaLcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundaLineaLcdActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(244, 157, 18));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(244, 157, 18));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Limpiar LCD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(72, 72, 72));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enviar datos LCD");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jButton4.setBackground(new java.awt.Color(244, 157, 18));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Enviar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSegundaLineaLcd)
                            .addComponent(txtPrimeraLineaLcd)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrimeraLineaLcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSegundaLineaLcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        sliderPwm.setBackground(new java.awt.Color(255, 255, 255));
        sliderPwm.setForeground(new java.awt.Color(195, 0, 0));
        sliderPwm.setMaximum(255);
        sliderPwm.setMinorTickSpacing(1);
        sliderPwm.setPaintLabels(true);
        sliderPwm.setPaintTicks(true);
        sliderPwm.setSnapToTicks(true);
        sliderPwm.setValue(0);
        sliderPwm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderPwmStateChanged(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(72, 72, 72));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PWM");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sliderPwm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sliderPwm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelContenido, 1204, 1204, Short.MAX_VALUE)
                    .addComponent(panelCargando, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panelCargando, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSegundaLineaLcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundaLineaLcdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundaLineaLcdActionPerformed

    private void cbxComboboxPuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxComboboxPuertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxComboboxPuertosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        panelCargando.setVisible(true);
        panelContenido.setVisible(false);
        hilo2 = new Thread(this);
        hilo2.start();
    }//GEN-LAST:event_formWindowOpened

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:

        if (cbxComboboxPuertos.getSelectedItem().equals("Seleccionar Puerto")) {
            JOptionPane.showMessageDialog(this, "Seleciona un puerto", "Debes tener un puerto seleccionado", JOptionPane.ERROR_MESSAGE);
        } else {
            port = (String) cbxComboboxPuertos.getSelectedItem();

            if (Conectar()) {
                btnConectar.setEnabled(false);
                btnDesconectar.setEnabled(true);

                JOptionPane.showMessageDialog(this, "Conectado al puerto serial: " + port);
                hilo1 = new Thread(this);
                hilo1.start();

            } else {
                JOptionPane.showMessageDialog(this, "Error de conexion", "No se pudo conectar al puerto serial: " + port, 0);
            }

        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void txtPrimeraLineaLcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimeraLineaLcdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimeraLineaLcdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiarCaracteres();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String texto = txtPrimeraLineaLcd.getText();
        enviarCaracteres(texto);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sliderPwmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderPwmStateChanged
        // TODO add your handling code here:
        int pwm = sliderPwm.getValue();
        enviarPwm(String.valueOf(pwm));
    }//GEN-LAST:event_sliderPwmStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String texto = txtSegundaLineaLcd.getText();
        enviarCaracteresSegundaLinea(texto);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        obtenerPuertosSeriales();
        cargarCombobox();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        // TODO add your handling code here:
        desconectar();
        btnConectar.setEnabled(true);
        btnDesconectar.setEnabled(false);
    }//GEN-LAST:event_btnDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JComboBox<String> cbxComboboxPuertos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCargando;
    private javax.swing.JLabel lblVoltajePotenciometro;
    private javax.swing.JPanel panelCargando;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelGraficaVoltaje;
    private javax.swing.JSlider sliderPwm;
    private javax.swing.JTextArea texAreaTecladoMatricial;
    private javax.swing.JTextField txtPrimeraLineaLcd;
    private javax.swing.JTextField txtSegundaLineaLcd;
    // End of variables declaration//GEN-END:variables

    private void obtenerPuertosSeriales() {
        arrayListPuertosSerial = new ArrayList<>();
        Enumeration comportIdentifier = CommPortIdentifier.getPortIdentifiers();

        while (comportIdentifier.hasMoreElements()) {
            CommPortIdentifier pid = (CommPortIdentifier) comportIdentifier.nextElement();
            if (pid.getPortType() == CommPortIdentifier.PORT_SERIAL) {
                arrayListPuertosSerial.add(pid);
            }
        }
    }

    private void cargarCombobox() {
        cbxComboboxPuertos.removeAllItems();
        cbxComboboxPuertos.addItem("Seleccionar Puerto");
        for (int i = 0; i < arrayListPuertosSerial.size(); i++) {
            CommPortIdentifier commPortIdentifier = arrayListPuertosSerial.get(i);
            cbxComboboxPuertos.addItem(commPortIdentifier.getName());
        }
        panelCargando.setVisible(false);
        panelContenido.setVisible(true);
        btnConectar.setEnabled(true);
        btnActualizar.setEnabled(true);
        cbxComboboxPuertos.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Puertos cargados correctamente");
    }

    private boolean Conectar() {
        boolean connet = false;
        for (int i = 0; i < arrayListPuertosSerial.size(); i++) {
            myCPI = (CommPortIdentifier) arrayListPuertosSerial.get(i);
            if (myCPI.getName().equals(port)) {
                connet = true;
                break;
            }
        }

        if (connet) {
            try {
                puerto = myCPI.open("Puerto Serial", 2000);
            } catch (PortInUseException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
            mySP = (SerialPort) puerto;
            try {
                mySP.setSerialPortParams(9600, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            } catch (UnsupportedCommOperationException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }

            return true;
        }

        return false;

    }

    void desconectar() {
        try {
            port = "";
            mySC.close();
            System.out.println("Close mySC");
            myPS.close();
            System.out.println("Close myPS");

            mySP.disableReceiveFraming();
            mySP.disableReceiveThreshold();
            mySP.disableReceiveTimeout();
            mySP.close();
            System.out.println("Close mySP");

            myCPI = null;

        } catch (Exception e) {
            System.out.println("Exception: " + e.getMessage());
        }
    }

    private void recibirDatos() {

        System.out.println("Conectado con el puerto serial " + port);
        // notificador.connet(true);
        while (!"".equals(port)) {
            try {
                mySC = new Scanner(mySP.getInputStream());
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                myPS = new PrintStream(mySP.getOutputStream());
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Creaccion de las variables de lectura y escritura");
            while (!mySC.hasNext()) {
                mySC.close();
                mySC = null;
                try {
                    mySC = new Scanner(mySP.getInputStream());
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            String cad = mySC.next();
            System.out.println("cad: " + cad);

            if (cad.contains("aje")) {
                int index = cad.indexOf("=");
                float voltaje = Float.parseFloat(cad.substring(index + 1, cad.length()));
                System.out.println("voltaje: " + voltaje);
                try {
                    //aplicamos patron observer de los patrones de diseño de sftware
                    //notificador.mostrarVoltaje(voltaje);
                    if (voltaje <= 5) {
                        //notificador.graficarVariacionVoltaje(list);
                        System.out.println("voltaje" + voltaje);
                        lblVoltajePotenciometro.setText(String.valueOf(voltaje));
                        graficar(voltaje);
                    }
                } catch (Exception e) {
                    System.out.println("exception: " + e.getMessage());
                }
            }
            if (cad.contains("cla")) {
                int index = cad.indexOf("=");
                char tecla = cad.charAt(index + 1);
                System.out.println("tecla: " + tecla);
                try {
                    texAreaTecladoMatricial.setText(texAreaTecladoMatricial.getText() + " " + tecla);
                    //  notificador.mostrarTecla(tecla);
                } catch (Exception e) {
                }
            }
        }
    }

    void enviarCaracteres(String string) {
        myPS.print("L" + string + "\r\n");
    }

    void enviarCaracteresSegundaLinea(String string) {
        myPS.print("D" + string + "\r\n");
    }

    void limpiarCaracteres() {
        String test = "L.\r\n";
        myPS.print(test);
    }

    void enviarPwm(String string) {
        myPS.print("P" + string + "\r\n");
    }

    int x = 0;

    private void graficar(double voltaje) {

        arrayVoltaje.add(voltaje);
        Datos.addValue(voltaje, "voltaje", String.valueOf(x++));

        freeChart = ChartFactory.createLineChart("Grafica del Voltaje", "tiempo", "voltaje ", Datos);
        ChartPanel panel = new ChartPanel(freeChart, true, true, true, true, true);

        //<editor-fold defaultstate="collapsed" desc=" Embellecimiento de la grafica (optional) ">
        //personalización del grafico color de fondo 
        System.out.println(freeChart.getPlot());
        CategoryPlot categoryPlot = (CategoryPlot) freeChart.getPlot();
        categoryPlot.setBackgroundPaint(Color.white);
        //personalización del grafico color de los grit 
        categoryPlot.setDomainGridlinePaint(Color.GRAY);
        categoryPlot.setRangeGridlinePaint(Color.GRAY);
        // -> Pinta Shapes en los puntos dados por el XYDataset
        LineAndShapeRenderer lineandshaperenderer = (LineAndShapeRenderer) categoryPlot.getRenderer();
        lineandshaperenderer.setBaseShapesVisible(false);

        //--> muestra los valores de cada punto XY
        CategoryItemLabelGenerator itmLabel = new StandardCategoryItemLabelGenerator();
        lineandshaperenderer.setBaseItemLabelGenerator(itmLabel);
        lineandshaperenderer.setBaseItemLabelsVisible(true);
        lineandshaperenderer.setBaseLinesVisible(true);
        lineandshaperenderer.setBaseItemLabelsVisible(false);
        //</editor-fold >

        panel.setBounds(panelGraficaVoltaje.getBounds());

        panel.setMaximumSize(new Dimension(683, 270));
        panel.setSize(new Dimension(683, 270));
        panel.setPreferredSize(new Dimension(683, 270));
        panelGraficaVoltaje.removeAll();
        panelGraficaVoltaje.setLayout(new BorderLayout());
        panelGraficaVoltaje.add(panel);
        panelGraficaVoltaje.validate();
    }

    @Override
    public void run() {
        Thread hiloActual = Thread.currentThread();
        if (hiloActual == hilo1) {
            recibirDatos();
        }

        if (hiloActual == hilo2) {
            graficar(0);
            obtenerPuertosSeriales();
            cargarCombobox();
        }

    }

}
